import { AlignCenter, AlignLeft, AlignRight, BringToFront, Layers, SendToBack, Trash2 } from "lucide-react";
import type { MoodboardDocument, MoodboardNode } from "../../types";

const SWATCH_COLORS = ["#ed6758", "#3f8f74", "#d4a43d", "#202422", "#ffffff"];

export function MoodboardInspector({ document, selectedNodeIds, selectedEdgeIds, onChange, onDelete, onBringToFront, onSendToBack }: { document: MoodboardDocument; selectedNodeIds: string[]; selectedEdgeIds: string[]; onChange: (document: MoodboardDocument) => void; onDelete: () => void; onBringToFront: () => void; onSendToBack: () => void }) {
  const selected = selectedNodeIds.length === 1 ? document.nodes.find((node) => node.id === selectedNodeIds[0]) : undefined;
  const selectedEdge = selectedEdgeIds.length === 1 ? document.edges.find((edge) => edge.id === selectedEdgeIds[0]) : undefined;
  const replace = (node: MoodboardNode) => onChange({ ...document, nodes: document.nodes.map((item) => item.id === node.id ? node : item) });
  return <aside className="moodboardInspector">
    <header><Layers size={17} /><strong>{selected ? "节点设置" : selectedEdgeIds.length === 1 ? "连线设置" : selectedNodeIds.length > 1 ? `已选 ${selectedNodeIds.length} 项` : "画板设置"}</strong></header>
    {selected?.type === "asset" && <section><h3>素材</h3><label>显示方式<select value={selected.data.fit} onChange={(event) => replace({ ...selected, data: { ...selected.data, fit: event.target.value as "cover" | "contain" } })}><option value="cover">填充</option><option value="contain">完整显示</option></select></label></section>}
    {selected?.type === "text" && <section><h3>文字</h3><label>字号<select value={selected.data.fontSize} onChange={(event) => replace({ ...selected, data: { ...selected.data, fontSize: event.target.value as "small" | "medium" | "large" } })}><option value="small">小</option><option value="medium">中</option><option value="large">大</option></select></label><label>颜色<input type="color" value={selected.data.color} onChange={(event) => replace({ ...selected, data: { ...selected.data, color: event.target.value } })} /></label><div className="moodboardAlignButtons"><button title="Left align" aria-label="Left align" onClick={() => replace({ ...selected, data: { ...selected.data, align: "left" } })}><AlignLeft size={15} /></button><button title="Center align" aria-label="Center align" onClick={() => replace({ ...selected, data: { ...selected.data, align: "center" } })}><AlignCenter size={15} /></button><button title="Right align" aria-label="Right align" onClick={() => replace({ ...selected, data: { ...selected.data, align: "right" } })}><AlignRight size={15} /></button></div></section>}
    {selected?.type === "swatch" && <section><h3>色块</h3><label>颜色<input type="color" value={selected.data.color} onChange={(event) => replace({ ...selected, data: { ...selected.data, color: event.target.value } })} /></label><div className="moodboardColorChoices">{SWATCH_COLORS.map((color) => <button key={color} type="button" aria-label={color} title={color} style={{ background: color }} onClick={() => replace({ ...selected, data: { ...selected.data, color } })} />)}</div><label>名称<input value={selected.data.name ?? ""} onChange={(event) => replace({ ...selected, data: { ...selected.data, name: event.target.value || undefined } })} /></label></section>}
    {selectedEdge && <section><h3>连线</h3><label>颜色<select value={selectedEdge.color} onChange={(event) => onChange({ ...document, edges: document.edges.map((edge) => edge.id === selectedEdge.id ? { ...edge, color: event.target.value as typeof edge.color } : edge) })}><option value="neutral">中性</option><option value="coral">珊瑚</option><option value="green">绿色</option><option value="gold">金色</option></select></label></section>}
    {!selected && selectedNodeIds.length === 0 && selectedEdgeIds.length === 0 && <section><h3>画板</h3><label>背景色<input type="color" value={document.backgroundColor} onChange={(event) => onChange({ ...document, backgroundColor: event.target.value })} /></label></section>}
    {(selected || selectedNodeIds.length > 1 || selectedEdgeIds.length > 0) && <footer><button type="button" title="Bring forward" aria-label="Bring forward" onClick={onBringToFront}><BringToFront size={16} /></button><button type="button" title="Send backward" aria-label="Send backward" onClick={onSendToBack}><SendToBack size={16} /></button><button className="danger" type="button" title="Delete selected elements" aria-label="Delete selected elements" onClick={onDelete}><Trash2 size={16} /></button></footer>}
  </aside>;
}
